version: '3'

services:
  openldap:
    image: osixia/openldap:1.5.0
    ports:
      - 389:389
      - 636:636
    environment:
      LDAP_ORGANISATION: "IOT"
      LDAP_DOMAIN: "iot"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_TLS: "false"
      LDAP_TLS_VERIFY_CLIENT: "try"
    volumes:
      - ./data:/var/lib/ldap
